# Generated by Django 2.1.5 on 2022-02-05 19:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0003_auto_20220205_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 5, 19, 41, 21, 269214, tzinfo=utc), verbose_name='date published'),
        ),
    ]
