# Generated by Django 2.1.5 on 2022-02-05 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0004_page_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
